// <auto-generated />
using System;
using InvoiceControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceControl.Data.Migrations
{
    [DbContext(typeof(InvoiceContext))]
    partial class InvoiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceControl.Domain.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Number")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("InvoiceControl.Domain.Models.InvoiceServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquot")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Amount")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("BasisCalculation")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CONFIS")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CSLL")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Credit")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("DateIssue")
                        .HasColumnType("date");

                    b.Property<decimal>("DeductionsValue")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("INSS")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("IRRF")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ISSValue")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("IntermediateIdent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IntermediateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("InvoiceNumber")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<decimal>("ItemValue")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("NoteValue")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("PASEB")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("PIS")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ServiceDesc")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal>("Taxes")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("UnitaryValue")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Invoice_Services", (string)null);
                });

            modelBuilder.Entity("InvoiceControl.Domain.Models.Provider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<long>("IdAdress")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StateRegistration")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAdress")
                        .IsUnique();

                    b.ToTable("Provider", (string)null);
                });

            modelBuilder.Entity("InvoiceControl.Domain.Models.Receiver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<long>("IdAdress")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StateRegistration")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAdress")
                        .IsUnique();

                    b.ToTable("Receiver", (string)null);
                });

            modelBuilder.Entity("InvoiceControl.Domain.Models.InvoiceServices", b =>
                {
                    b.HasOne("InvoiceControl.Domain.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceControl.Domain.Models.Receiver", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("InvoiceControl.Domain.Models.Provider", b =>
                {
                    b.HasOne("InvoiceControl.Domain.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("InvoiceControl.Domain.Models.Provider", "IdAdress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CT_Provider_Addresss");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("InvoiceControl.Domain.Models.Receiver", b =>
                {
                    b.HasOne("InvoiceControl.Domain.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("InvoiceControl.Domain.Models.Receiver", "IdAdress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CT_Receiver_Addresss");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
